### ISSUE TITLE
Split delegation application into BHEAD

### ISSUE THREAD

**Issue by nc6** [input-output-hk/cardano-ledger#1007]
https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1573110538434600

Currently delegation application (e.g. activating scheduled delegations) is done within the BBODY rule tree. This presents an inconsistency between the spec and the implementation in terms of when delegations are activated - the implementation runs BBODY rules _before_ protocol application, so activations happen on slot `n`. But in the spec, protocol processing happens before `BBODY`, so delegations are activated on slot `n+1`.

As per the time travel property, there should not be anything happening in BBODY which takes immediate effect. So the correct solution is to move this to the BHEAD tree and have the activations take place on the slot tick

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
