### ISSUE TITLE
Mismatch between formal and executable UProp type and UPPVV rule

### ISSUE THREAD

**Issue by jmhrpr** [input-output-hk/cardano-ledger#1024]
In the [executable ledger spec](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/byron/ledger/executable-spec/src/Ledger/Update.hs) the UProp type doesn’t seem to have a field for the update proposal size despite an abstract function “upSize” being defined in the [formal ledger spec](https://hydra.iohk.io/build/1243914/download/1/ledger-spec.pdf) Chapter 6.1, p.20, Figure 20. Following this, in the formal ledger spec Chapter 6.2, p.23, Figure 25: Update proposals validity rules, the proposal size is checked against the maxProposalSize which is defined in the protocol parameters. This is not implemented in the executable spec.

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
