### ISSUE TITLE
Mismatches in specification of PParams

### ISSUE THREAD

**Issue by wuggen** [input-output-hk/cardano-ledger#1031]
The text of the Byron formal spec specifies a `txFeePolicy` key in the PParams type ([here](https://github.com/input-output-hk/cardano-ledger-specs/blob/d634cfa2864f73e83974dc3c673bfc66de4a7c3a/byron/ledger/formal-spec/update-mechanism.tex#L166)) that is not mentioned in the figure listing the keys ([here](https://github.com/input-output-hk/cardano-ledger-specs/blob/d634cfa2864f73e83974dc3c673bfc66de4a7c3a/byron/ledger/formal-spec/update-mechanism.tex#L194)).

Additionally, the keys `bkSgnCntT` and `bkSlotsPerEpoch` are implemented in the executable spec ([here](https://github.com/input-output-hk/cardano-ledger-specs/blob/d634cfa2864f73e83974dc3c673bfc66de4a7c3a/byron/ledger/executable-spec/src/Ledger/Update.hs#L107)) but not mentioned in the formal spec. These should be constant values and hence not updateable parameters.

(Issue brought up during audit meeting a couple weeks ago.)

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
