### ISSUE TITLE
Potential DoS vulnerability in design of software version update proposals

### ISSUE THREAD

**Issue by wuggen** [input-output-hk/cardano-ledger#1032]
Currently, the rules for proposal registration allow for only one proposal to be registered for a particular software version at a given time, and the updated version must be incremented by exactly 1. This could allow an adversary to continually (re)submit a spurious proposal and prevent the legitimate developers from ever submitting their own.

This is only a vulnerability if arbitrary parties are allowed to submit update proposals. This is not the case in Byron and I am told it will not be the case in Shelley until research regarding its safety is completed. This issue is submitted as a consideration for the research team.

(Issue raised in audit meeting a couple weeks ago.)

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
