### ISSUE TITLE
Inconsistent variable naming between ledger executable and formal specs in Ch8.3 UTxO Properties

### ISSUE THREAD

**Issue by jmhrpr** [input-output-hk/cardano-ledger#1107]
In Chapter 8.3 of the [formal ledger spec](https://hydra.iohk.io/build/1243914/download/1/ledger-spec.pdf),  Property 1 (No double spending), there is a small inconsistency between the variable names used compared to the ones used in the [executable spec](https://github.com/input-output-hk/cardano-ledger-specs/blob/01f1f22f707d990ee765a1d351ef75cc9ff75a17/byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs#L37). Functionality isn't affected.

In the formal spec `i<j` is used, as highlighted in the image below, where as in the executable spec the code works as `j<i`.

![image](https://user-images.githubusercontent.com/25673452/71819990-94981580-3085-11ea-8c70-175ebfdf94db.png)

**Comment by JaredCorduan** [comment]
thank you @jmhrpr :)

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
