### ISSUE TITLE
Hashing choices

### ISSUE THREAD

**Issue by redxaxder** [input-output-hk/cardano-ledger#1323]
There are places where non-transmitted data is hashed.
These makes the hashing ambiguous without a canonical encoding.

- [ ] Shelley.Spec.Ledger.BlockChain (mkSeed)
  - list token for the the tuple
- [x] Ledger.UTxO (fromTxOuts)
  - list token wrapping the address
- [x] Shelley.Spec.Ledger.Scripts (hashAnyScript) 
  - the leading word8
- [x] Shelley.Spec.Ledger.LedgerState (genesisId)
  - the whole thing, i think

We should find a way to make sure these don't cause trouble. Getting rid of them, transmitting them, or standardizing them.

**Comment by JaredCorduan** [comment]
https://github.com/input-output-hk/cardano-ledger/blob/b407d030146c7bba21da1c7bd7c953f8d5b09c02/libs/cardano-protocol-tpraos/src/Cardano/Protocol/TPraos/BHeader.hs#L450
