### ISSUE TITLE
Decision: when should pool members be notified of a drop in desirability

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-ledger#386]
We state that a wallet should notify its user when the pool they have delegated to becomes less desirable -- i.e., when it would be beneficial to delegate to another pool.

We need to specify exactly when this should happen (how many places the pool would have to drop, ...), so that we don't prompt frequent switching, but also get people to switch when they really should.

**Comment by JaredCorduan** [comment]
There are research streams for this, it is being tracked and discussed elsewhere
