### ISSUE TITLE
Check independence of Delegation, Update, and UTxO STS's

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger#755]
We plan on testing invalid chains that contain only one type of invalid payload. This enables us to have simpler generators, and explore a smaller state space. However, to make sure we're not missing important cases, for instance errors in different STS's that cancel each other, we must test that the update in one STS does not affect the other. 

We could test independence up to 2k blocks forward, or simply independence up to 1 block forward (which might result in tests that are easy to write, and faster to execute).

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
