### ISSUE TITLE
Mismatch between formal and executable UPIEC rule

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/cardano-ledger#970]
In the formal spec ([link](https://hydra.iohk.io/build/1243914/download/1/ledger-spec.pdf)), the `UPIEC` rule (Rule 49, Fig. 45, p. 39) leaves `raus` unchanged in the state. In the executable spec, they are instead emptied ([link](https://github.com/input-output-hk/cardano-ledger-specs/blob/4ac516ce06a04a9eef494f40b9a81e12c30c4011/byron/ledger/executable-spec/src/Ledger/Update.hs#L1651)).

**Comment by csoroz** [comment]
Seems to be fixed in the current formal spec: https://hydra.iohk.io/build/3744972/download/1/ledger-spec.pdf
<img width="494" alt="Screenshot 2020-08-09 at 23 09 25" src="https://user-images.githubusercontent.com/3624828/89741900-71a76700-da95-11ea-90d4-6652daa370b2.png">

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
