### ISSUE TITLE
Mismatch between formal and executable UTXOW rule

### ISSUE THREAD

**Issue by troedfach** [input-output-hk/cardano-ledger#971]
In the formal ledger spec ([link](https://hydra.iohk.io/build/1243914/download/1/ledger-spec.pdf)), Chapter 4.1, p.12, Figure 10: UTxO with witnesses inference rules, the size of the transaction is checked against the maxTxSize as defined in the protocol parameters. This is not implemented in the executable spec (UTXOW rule [here](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs)).

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
