### ISSUE TITLE
Throwable vs error in ADELEG 

### ISSUE THREAD

**Issue by Vtec234** [input-output-hk/cardano-ledger#987]
In the ledger specification, the ADELEG rule should always succeed, because the logical disjunction/OR of the preconditions of its two variants is true. Then, in the implementation, if we fail at the end of the second variant, this is treated as an error - ([link](https://github.com/input-output-hk/cardano-ledger-specs/blob/ce0fc635fa3b022a9a4cb49af2ca366683596cac/byron/ledger/executable-spec/src/Ledger/Delegation.hs#L398)). A question that arose during the audit is what happens on line 397 - since `S_AfterExistingDelegation` is thrown, can it be handled? If not, perhaps it should also be an `error`.

**Comment by dnadales** [comment]
> A question that arose during the audit is what happens on line 397 - since S_AfterExistingDelegation is thrown, can it be handled?

If I understand this correctly, the question is what happens on line 397 if `sp >= s` doesn't hold. However this shouldn't be possible since rules are tried in the order in which they appear in the `transitionRules` list, and in the rule that precedes this one:

```haskell
    , do
        TRC ( _env
            , st@DState { _dStateDelegationMap = dms
                        , _dStateLastDelegation = dws
                        }
            , (s, (vks, vkd))
            ) <- judgmentContext
        if vkd ∈ range dms
          then return st
          else do
            case Map.lookup vks dws of
              Just sp -> sp >= s ?! S_AfterExistingDelegation
              Nothing -> error $  "This can't happen since otherwise "
                               ++ "the previous rule would have been triggered."
            return st
```

We have the following checks:

```haskell
        vkd ∉ range dms ?! S_AlreadyADelegateOf vkd (dms !> vkd)
        case Map.lookup vks dws of
          Nothing -> pure () -- If vks hasn't delegated, then we proceed and
                             -- update the @ADELEG@ state.
          Just sp -> sp < s ?! S_BeforeExistingDelegation
```

So if the previous check failed because `vkd ∈ range dms`, then we will return `st` in the last rule. If `vkd ∉ range dms`, then we will perform the `Map.lookup vks dws`. If this returns `Nothing`, then the rule succeeds and we're golden. If it returns `Just sp` and `not (sp < s)` we're in a situation where (doing some notational abuse):

```haskell
vkd ∉ range dms && Map.lookup vks dws == Just sp && sp >= s
```

So if I got this right,  it cannot be the case that the `S_AfterExistingDelegation` is thrown. On the other hand, if this makes sense, we could replace `S_AfterExistingDelegation` by an error explaining why this cannot happen. 

What do you think?

**Comment by dcoutts** [comment]
Having the result be independent of the order of evaluation of the two guarded cases does have a nice symmetry. Perhaps we just need to be more explicit in the comments that it must be the case that A or B, so each one is a guarded A | ... ;  B | ..., but one of them must succeed, and the order in which they are tried does not matter (though in practice we use top to bottom).

**Comment by Vtec234** [comment]
> On the other hand, if this makes sense, we could replace S_AfterExistingDelegation by an error explaining why this cannot happen.

Thanks for the thorough walkthrough! Although I seem to have obfuscated it with a poor explanation, this was my point exactly - perhaps an `error` would be a better indication of unreachability.

> Having the result be independent of the order of evaluation of the two guarded cases does have a nice symmetry.

If I'm not mistaken, it seems that this symmetric alternative would require replacing the existing `error` with a thrown `S_NoLastDelegation`. Otherwise, when evaluated first, the second rule could fail without redirecting to the other rule.

**Comment by dnadales** [comment]
> an error would be a better indication of unreachability.

Yes! I totally agree. This was an excellent point. Thanks!

@mhuesch would replacing `S_AfterExistingDelegation` by `error` affect the goblins? (I guess not since you were ignoring the `S_` prefixed failures)

**Comment by nc6** [comment]
I'd be more inclined to replace the `error` with an `S_NoLastDelegation`, because this would provide the symmetry (even if we know that such a case is unreachable).

**Comment by dnadales** [comment]
But won't that confuse people again? The rules hint that such errors are possible, whereas is not easy to see that they aren't. I think `error` communicates the intent more clearly here.

**Comment by mhuesch** [comment]
We provide the goblins with a list of desired PredicateFailure’s, as targets, so we can exclude the “structural” PFs, or the error call if that’s what we replace it with.

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
